apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  namespace: myapp
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: myapp

